server:
  contextPath: /tightening
  port: 8888
  use-forward-headers: true

slack:
  # Get a token for your team from https://api.slack.com/custom-integrations/legacy-tokens
  token: 

active-directory:
  application:
    application-id: 8e51f213-73b1-46aa-8c8b-743d847d3184
    client-secret-key: byDGoOsn4e/4qTRqBc5KdiR80eNVw4tlemSq1Z+Dy3c=

redirect:
  host: localhost
  uri: http://${redirect.host}${server.contextPath}/authorize
